dashboard:
   path: /dashboard
   controller: App\Controller\DashboardController::index

tela_login:
   path: /telalogin
   controller: App\Controller\TelaLoginController::index

home:
  path: /
  controller: App\Controller\HomeController::home   
